import React from "react";
import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const Terms: React.FC = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen pt-24 pb-12 px-6 max-w-4xl mx-auto">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white rounded-[2rem] p-8 md:p-12 shadow-xl"
            >
                <button
                    onClick={() => navigate(-1)}
                    className="flex items-center text-gray-500 hover:text-[#004E89] mb-8 transition-colors font-medium"
                >
                    <ArrowLeft className="w-5 h-5 mr-2" />
                    Back
                </button>

                <h1 className="text-3xl font-bold text-[#004E89] mb-6">Terms and Conditions</h1>

                <div className="space-y-6 text-gray-600 leading-relaxed">
                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-2">1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using this service, you accept and agree to be bound by the terms and provision of this agreement.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-2">2. Usage Rights</h2>
                        <p>
                            We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Site. Any unauthorized use terminates the permission or license granted by us.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-2">3. User Data & Privacy Policy</h2>
                        <p>
                            Your privacy is very important to us. All personal data such as preferences and itineraries are generated and handled explicitly to provide personalized experiences.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-gray-800 mb-2">4. Disclaimers</h2>
                        <p>
                            The recommendations generated by our AI are for informational purposes. Users are expected to verify travel routes, pricing, and availability before embarking on trips.
                        </p>
                    </section>
                </div>
            </motion.div>
        </div>
    );
};

export default Terms;
